### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by mrunankpawar** [Club-TechBrewers/Club-TechBrewers.github.io#52]

**Comment by RuchirDixit** [comment]
Hey can you please assign this issue to me.

I would like to add Issues and PR section to this Contribution.md file which I feel is missing currently. In this section, we will setup guidelines for an issue whether it is Feature/Bug/Documentation issue and a few other guidelines as well.

**Comment by mrunankpawar** [comment]
Hey Ruchir, assigning you the issue. Please go ahead and contribute!
