### ISSUE TITLE
Change font-size of text in footer

### ISSUE THREAD

**Issue by mrunankpawar** [Club-TechBrewers/Club-TechBrewers.github.io#73]
The font size of the text in the footer is too large, so reduce the font size of `<p>` tag and `<a>` tag of contact us in the footer.

<img width="1416" alt="Screenshot 2023-01-29 at 9 42 30 AM" src="https://user-images.githubusercontent.com/65391854/215304579-26a8b913-42a5-4412-9ffc-6f128341996f.png">

**Comment by shyamtawli** [comment]
@mrunankpawar Please assign me I want work on this.

**Comment by mrunankpawar** [comment]
Hey, I have assigned you this task. Please make sure to add in screenshots once you have made the changes.

**Comment by codewithbharat** [comment]
@mrunankpawar I would like to work on this issue pleases assign me

**Comment by shyamtawli** [comment]
@codewithbharat Sorry Bro I am working on it.

**Comment by codewithbharat** [comment]
@shyamtawli ok bro... Go for it
