### ISSUE TITLE
Event Alert pop-up on Home Screen

### ISSUE THREAD

**Issue by mrunankpawar** [Club-TechBrewers/Club-TechBrewers.github.io#78]
The Event Alert pop-up should be displayed on the Home Screen which says, **"New Event is happening, for more info visit Events Page."** This pop-up will be closed automatically after few seconds. Also keep in mind to make it mobile-friendly as well!

This code doesn't actually need to be connected to events page, but manually we can comment the code when event is not there and uncomment it whenever we schedule the event. 

While making the Pull request please make sure that you are adding screenshots of the pop-up you have developed on the Home Screen.

**Comment by manisanghsharma** [comment]
Hello, I would like to work on this enhancement

**Comment by mrunankpawar** [comment]
Hey @manisanghsharma, assigning you the issue, please go ahead and contribute!

**Comment by manisanghsharma** [comment]
- #81 
---

**Comment by mrunankpawar** [comment]
Thank you so much for your contribution @manisanghsharma !

**Comment by mrunankpawar** [comment]
Just noticed that, in the recording the pop-up seems to be in the centre but after the deployment, it's actually at the top-left corner. Can you please look into it @manisanghsharma !

**Comment by mrunankpawar** [comment]
Just noticed that, in the recording the pop-up seems to be in the centre but after the deployment, it's actually at the top-left corner. Can you please look into it @manisanghsharma !

**Comment by manisanghsharma** [comment]
Sure, I will take a look

**Comment by manisanghsharma** [comment]
https://github.com/Club-TechBrewers/Club-TechBrewers.github.io/assets/78167300/7b58bece-d581-44f2-825e-9b15675ddfe6

Just gave it a check, it seems to be fine in my browser and my mobile. Can you look at it once again?

**Comment by mrunankpawar** [comment]
Yep, just checked. Sorry for the inconvenience
